name: python-tests

on:
  pull_request:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install local source package
      run: pip install -e .
    
    - name: Install optional dependencies
      run: pip install -e ".[testing,notebook,linting]"

    - name: Run python unit tests
      run: cd test && pytest .